# https://github.com/vuejs/vue-next - b716a906fe51e82a1b3f82cf538b67abdaf66154

ls:
  .js: kebab-case | PascalCase | camelCase
  .ts: camelCase
  .d.ts: kebab-case
  .mock.ts: kebab-case
  .spec.ts: camelCase
  .test-d.ts: kebab-case
  .config.js: kebab-case
  .umd.js: kebab-case
  .spec.ts.snap: camelCase

  scripts:
    .js: camelCase

ignore:
  - node_modules
  - dist
  - .git
  - .github
  - .vscode
  - .eslintrc.js
